spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${db.host}:${db.port}/${db.schema}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    '[com.f7dec8]': debug